server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:auth_user}
    password: ${SPRING_DATASOURCE_PASSWORD:auth_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:ecommerce-super-secret-jwt-key-change-this-in-production-must-be-256-bits}
  expiration-ms: 900000
  refresh-expiration-ms: 604800000
